name: Difference-Graph-Test-1-prime_MINUS_1-4-multiples

on:
  workflow_dispatch:
    inputs:
      n:
        description: '분포 그래프 그릴 자연수 (~까지) (3 이상의 자연수)'
        required: true
        type: string

run-name: Difference Graph [ ${{ github.event.inputs.n }} ]

jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: pip install matplotlib
      run: pip install matplotlib
    - name: Run difference-graph.py
      run: python difference-graph.py ${{ github.event.inputs.n }}
